model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
file_opener = "none"
show_raw_agent_reasoning = true

[tools]
web_search = true

sandbox_mode = "workspace-write"
approval_policy = "on-request"   # The model decides when to escalate the approval

# Extra settings that only apply when `sandbox = "workspace-write"`.
[sandbox_workspace_write]
# Allow the command being run inside the sandbox to make outbound network
# requests. Disabled by default.
# Stop getting prompted when your tests running want to access the internet or when its trying to curl outside documentation.
network_access = true
# Permanently allow writes to global caches:
writable_roots = [
  "/Users/jessfraz/.cache",
  "/Users/jessfraz/.cache/pip",
  "/Users/jessfraz/.cache/uv",
  "/Users/jessfraz/.cargo",
  "/Users/jessfraz/.rustup",
  "/Users/jessfraz/.yarn",
  "/Users/jessfraz/.npm",
  "/Users/jessfraz/.local/share/pnpm", # pnpm store lives here by default
]

[shell_environment_policy]
inherit = "all"                # This is the default value. Inherit all environment variables.
ignore_default_excludes = true # Do not ignore any environment variables by default, allows it to see shit like tokens, which if you are running tests and it needs variables you will want.
