model_reasoning_effort = "high"
model_reasoning_summary = "detailed"
file_opener = "none"
show_raw_agent_reasoning = true

[tools]
web_search = true

sandbox_mode = "workspace-write"
approval_policy = "on-request"

# Extra settings that only apply when `sandbox = "workspace-write"`.
[sandbox_workspace_write]
# Allow the command being run inside the sandbox to make outbound network
# requests. Disabled by default.
network_access = true

[shell_environment_policy]
inherit = "all"
