
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-06-27T11:39:43-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "409eb0c633cff6ee56a985b6eb74e0093e84de78",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
