
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-06-09T14:17:50-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "5cf77b630894afc6ebd6138bdf30c1babe8b3098",
 "version": "1.0.0b11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
