workspace(name = "intellij_with_bazel")

# The plugin api for IntelliJ 2016.1.3. This is required to build IJwB,
# and run integration tests.
new_http_archive(
    name = "intellij_latest",
    build_file = "intellij_platform_sdk/BUILD.idea",
    url = "https://download.jetbrains.com/idea/ideaIC-2016.2.4.tar.gz",
)

# The plugin api for CLion 2016.1.3. This is required to build CLwB,
# and run integration tests.
new_http_archive(
    name = "clion_latest",
    build_file = "intellij_platform_sdk/BUILD.clion",
    url = "https://download.jetbrains.com/cpp/CLion-2016.2.2.tar.gz",
)

# The plugin api for Android Studio 2.2 stable. This is required to build ASwB,
# and run integration tests.
new_http_archive(
    name = "android_studio_latest",
    build_file = "intellij_platform_sdk/BUILD.android_studio",
    url = "https://dl.google.com/dl/android/studio/ide-zips/2.2.0.12/android-studio-ide-145.3276617-linux.zip",
)

maven_jar(
    name = "junit",
    artifact = "junit:junit:4.11",
    sha1 = "4e031bb61df09069aeb2bffb4019e7a5034a4ee0",
)
