
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-08-13T11:42:18-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "46e1b758bc3694df7b4f08f24b62e73c59494f73",
 "version": "4.3.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
